trigger:
  branches:
    include:
      - main
  paths:
    include:
      - main.py
pool:
  name: my-ubuntu-pool  # Specify the name of your custom agent pool here

steps:
  - script: |
      git clone https://github.com/Guyashkenazi6/profileapp.git
      docker build -t $(DOCKERHUB_USERNAME)/profile-app .
      echo $(DOCKERHUB_PASSWORD) | docker login -u $(DOCKERHUB_USERNAME) --password-stdin
      docker push $(DOCKERHUB_USERNAME)/profile-app
    displayName: 'Build and Push Docker Image'


