version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

  build:
    commands:
      - echo Building Docker image...
      - docker build -t guyashkenazi/profile-app:latest .

  post_build:
    commands:
      - echo Running tests...
      - docker run guyashkenazi/profile-app:latest test_app.py
      - echo Tests completed successfully!
      - echo Pushing Docker image to Docker Hub...
      - docker push guyashkenazi/profile-app:latest

artifacts:
  files: []
  discard-paths: yes

cache:
  paths: []
