apiVersion: apps/v1
kind: Deployment
metadata:
  name: guymain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guymain
  template:
    metadata:
      labels:
        app: guymain
    spec:
      containers:
      - name: guymain
        image: guyashkenazi/profile-app
        ports:
        - containerPort: 5000
